* 摘抄
** 学习数学的方法
- 原理篇：
   1. 学习数学在于构造自己的体系（数学世界观），你自己不主动，只是往里面硬塞东西是没用的。先把初心找回来吧。心理上学习有一个大敌：害怕努力！为什么害怕努力？因为人无法面对即使自己尽了全力仍然失败的结果。如果我不尽全力，失败也有一个好借口，这是万万不可的，可是这是很多人不努力的根本原因。做不出问题不要觉得自己笨，因为智力也好都是浮动的。要把失败归结于自己的思考本事，不要给自己贴标签，伤害自己的感情。
   2. 画一个小圆而不是大圆（先求精再求广）。人类的大脑的一个基本特点是重视联系，一个新的东西只有和别的东西结合的越深才能更好地被理解和记忆。碰到新的概念和结果要一步一个脚印写得透透的。这个概念为什么会出现？它和旧的概念和结果是什么关系？要思考到什么程度？最好的就是，如果换你来你也得这样定义！思考这些问题的记得动笔，动笔的意义在于刺激你思考。而且人类的大脑像cpu而不是硬盘，擅长处理不擅长记忆，写在纸上吧！不要装逼！把一个个结果和定理在脑海中编织成一个网，去思考网上任意两点之间的联系，联系越大，你的理解越深。你也越难忘记这些结果，不会发生考完试就还给老师的事情。记住！数学和其它的专业不同，前后课程的联系很大，如果你基础不牢，后面地动山摇。


- 方法篇：
  1. 做笔记：前面我提过学习数学要构造自己的体系，这里的笔记就是你脑海中体系的具体化，说白了，这就是你写给自己的教科书。不是简单的抄录书本，也不是只是自己对一两个问题的理解。而是要写得完备，有一个比较清晰的体系。我推荐使用onennote等电子笔记来完成这项工作，这样方便修改和保存。知乎上也有相关的问题，你可以参考。如何充分利用 OneNote，发挥它的全部价值和潜力？ - 笔记类应用
  2. 重复和熟悉。
     - 冯 诺伊曼： 年轻人，在数学里，你不能真正理解一个东西，习惯它吧。
     - 希尔伯特： 5遍，起码5遍！
     - 孔子：学而时习之，不亦乐乎。如果你学某个新的数学工具（概念，定理），你要不断的使用它。最简单的方法就是做题，我推荐作大数学家的一些习题集，这些习题本身就是会帮助你构造体系。理解不同概念之间的联系。我自己做的是方向和分析pde有关，所以我只推荐相关的教材和习题：pde：先做evans，然后再去搞定trudinger，pde里面有些东西懂不懂泛函分析都能看（极值原理这些东西），有些必学先学泛函分析。起码学过sobolev space再说，更别提什么复／实插入空间了。
     - 分析：rudin三本书足够了，主要把精力放在第一本《数学分析原理》和第二本《实分析和复分析》。第三本太不人道了，我其实不太推荐。如果真的学一些实用的泛函分析第二本就够了，我不推荐rudin，从拓扑向量空间讲起实在是呵呵.
  3. 不要太拘泥于教材，既然是构筑体系，那么要以我为主，什么书你觉得最合你的心意，你就选那个教材。把它的想法吸收进你的体系。不停的修改你的体系，慢慢的体系就能融合进你的头颅了。当然了，体系有好有坏，我推荐的书是个人感觉很清新的。
  4. 不停的使用你的体系去解决问题，不停的使用新的概念，熟悉它，把它变成你的某种本能。
  5. 制定计划和执行：数学是需要天天学月月学年年做的事情。所以要养成每天都学的好习惯。按照自己的时间表学习。我推荐你看《习惯的力量》等靠谱的书来帮你养成习惯。当然了，你真有动力，这些都不需要。
* 感想
** 我的规划
   :LOGBOOK:
   CLOCK: [2018-04-05 Thu 09:23]--[2018-04-05 Thu 09:24] =>  0:01
   :END:
- *每个人都有好的规划，但是因为各种私意阻拦而付之东流。因此必须采用非常手段克服私欲，这样才能成功，就是所谓的格君心。我决定吧自己的意志交给emacs。加一个缓冲器，这样才能明确感知到这些私欲，做更好的自己。*
- 具体做法：
  1. 有什么做法先在emacs中列好，有计划就加上去。
  2. 执行某项任务的时候加个计时器，计算自己说做的努力，做完后进行评分。
  3. 若突然想做某件事的时候，将计划加入emacs中。然后统一时间进行决定判断。
- 作息时间表：
  1. 每天7:30起床。8:30之前起床吃完早餐，然后安排好今日大致计划（中途可以对计划进行增删）
  2. 每天看qq，邮件，知乎的时间为吃饭时间前后。
  3. 每天22:30进行每日总结，然后将东西都上传到emacs中。
  4. 关于娱乐放松，统一放在11:00-12:00,这样充实的一天才能够尽情的玩乐。












