#+TITLE:This document is about my thought
* Apperception
**  人生的方向 - [2018-10-25 四  10:35] 
  *四念处：观身不净，观受是苦，观心无常，观法无我* 
 
循着前人的脚步，不断前行，勇猛精进，一刻不能放松
**  畏惧任务 - [2018-10-28 日  09:44] 
  *每次到任务时就开始畏惧* 
每次要做规划好的计划的时候就开始畏惧，找各种接口推脱到明天，哪有什么借口，能被推脱只能说明自己不用心，面对自己喜欢的事物，即使在大的借口也不会放弃，总会想办法达成，不喜欢的事，再小的动静也能成为借口。没有借口，只有想不想。对使自己变好的计划，必须不折不扣的执行。每次记录，每次找原因改善，一定要做自己的主人。
总是畏惧别人的眼光，想法。没有做亏心事，没做错什么，又有什么好畏惧的，何必拿别人的想法来约束自己。

反观觉照 
**  勇猛精进 - [2018-11-04 日  14:39] 
  *人生在世，只能靠自己，而且可以靠自己* 
最近反思过去，发现很多事情当时主动一点，勇猛精进一点，现在也可以完全不同。
很多事情不是很难，而是不能持之以恒的，但又必须进行不断选择，才能选到合适的。人生的悖论就在这儿，打破悖论的方法就是进行信息的全面收集，这样才能少走弯路。做什么事情，进行任何选择前，必须尽自己所能，进行信息的收集整理。
 

世界有很多可能，不要自怨自艾，只管勇猛精进，不断向前

人生的训练离不开经验的积累（数据），而获取数据性价比最高的方法就是学习知识。我爱学习，尽可能学到更多的知识。
**  知道 - [2019-04-21 周日  21:06] 
  *知之为知之不知为不知 是知也 -杨振宁的话对这句话的新理解* 
只有知道自己知道的范围，以及还不知道的范围才能说真真学到了知识，而不是什么都模模糊糊，都是一个糊涂账。
而不知道的范围也是以后自己前进的方向。
渗透式学习，不要因为不知道就不去了解，一次次接触，一次次渗透渐渐也就懂了
（杨振宁老先生也说讲座有很多他是不懂得，多听听也就知道个大概了） 
**  自己最重要 - [2019-05-30 Thu 08:59] 
  *克服自己的怯懦* 
在以前，总是对别人的看法有许多顾虑，貌似自己特立独行，原来自己还是很怕影响捣别人，害怕别人的指责。导致很多事不敢尝试，怕尝试，怕失败后别人的看法，现在看来实在太荒谬了。以后一切以自己为重。现代社会都是以结果为导向，而不是以过程。要全心全意为自己的内心服务。没有什么比强大自己内心更重要。
**  不自信的事不要随便说出来 - [2019-06-03 Mon 15:11] 
  *不要夸夸其谈* 
如果一件事 自己都没有兴趣
如果一件事 自己都无法说服
如果一件事 自己都讨厌
如果一件事 自己都觉得不可能
不要表达出来丢人现眼
不要相信自己以为的，任何事要有自己独立的判断
* Understanding of events
**  立志 - [2018-10-28 日  09:26]
  *小人常立志，君子立常志* 
一直以来，各大圣贤都强调立志的作用，自己也经常立志，但立过就忘，甚至变得变本加厉。我此次又准备立志，一定要时时提醒自己，不要怕，不行就把它当初一次错误的实验，找出问题，下一次改进。
不管怎样，都要做一个心中志向坚定的人。
**  [2019-06-06 Thu 15:56] -  英语听力练习
  *提高自己的英语听力* 
突然发现，听力的 80%词汇都认识，但就是听不出来，是听少了，而不是单词的原因。
提升听力的唯一方法就是多听，多听，还多听
只有听得足够多的例子，才会强化自己的泛化能力，英语听力才会提高，不然一直过拟合。
* extract
** 法律是为国家利益服务的
** 绝不要把目光移开 - [2019-06-01 Sat 10:35] 
无论遇到什么，都正视它 
** 追果索因 - [2019-06-01 Sat 15:29] 
任何事情都是有缘由的，要保持探索的好奇心，追寻其中缘由，把知识活用
知识不是死的，都很鲜明，要学会灵活应用。
** 人生最大的谎言 -你不行 - [2019-06-04 Tue 18:57] 
人生最大的谎言就是你不行，那些失败者告诉你你不行，因为他们也没有做到，那些成功者也企图告诉你你这样子不行，可他们也只走了万千成功之路的其中一条，要记住，唯一能说你不行的人只有你自己.人生的一大错觉是你以为你行，人生还有一个错觉更要命，那就是你以为你不行。  
